# Generated by Django 2.2.4 on 2019-08-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=255, unique=True)),
                ('translation', models.CharField(max_length=255)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('is_passed', models.BooleanField()),
            ],
        ),
    ]
