# Generated by Django 2.2.4 on 2019-08-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
