# Generated by Django 2.2.4 on 2019-08-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190824_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
